name: "Manual"

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to undo commit'
        required: true
        default: 'add'

jobs:
  Undo:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: main

      - name: Checkout private tools
        uses: actions/checkout@v2
        with:
          run: |
            cd main
            git checkout add
            git config --global user.name 'github-actions[bot]'
            git config --global user.email 'github-actions[bot]@users.noreply.github.com'          
            git reset --hard 'HEAD~1'
            git push --force
