name: "Manual2222"

on:

  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to undo commit'
        required: true
        default: 'add_check_commit'

jobs:
  Undo:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        with:
           ref: ${{ github.event.inputs.branch }}
           fetch-depth: 0 

      - name: Undo Push
        uses: actions/checkout@v2
        run: |
          git checkout add
          git reset --hard 'HEAD~1'
          git push --force
