name: "Manual"

on:

  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to undo commit'
        required: true
        default: 'add_check_commit'      
      cos:
        description: 'cos2'
        required: true
        default: 'cos2'

jobs:
  Undo:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        with:
           ref: ${{ github.event.inputs.branch }}
           fetch-depth: 0

      - name: strig
        run: echo ${{ github.event.inputs.branch }} && ${{ github.event.inputs.cos }}
    
      - name: Undo Push
        uses: exions/undo-push@v1
        with:
          branch: ${{ github.event.inputs.branch }}
